[package]
name = "ai-client"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
serde = { version = "1.0.219", features = ["derive"] }
reqwest = "0.12.22"
config = { path = "../config" }
serde_json = "1.0.141"