[workspace]
resolver = "2"
members = [ "ai-client",
    "config", "http","http-analyze",
    "http-collect", "repository-click-house", "repository-click-house-macro", "service-analyze", "service-collect",
]
