[package]
name = "service-analyze"
version = "0.1.0"
edition = "2024"

[dependencies]
ai-client = { path = "../ai-client" }
async-trait = "0.1.88"
chrono = "0.4.41"
anyhow = "1.0.98"
serde_json = "1.0.141"
serde = { version = "1.0.219", features = ["derive"] }
log = "0.4.27"